---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test .drone.yml
  image: suzukishunsuke/jsonnet-check:v1.1.2-v0.1.1
  settings:
    format: true
    stream: true

---
kind: pipeline
name: build-0.11.14__8.5.4

platform:
  os: linux
  arch: amd64

steps:
- name: build and push docker
  image: plugins/docker:18.09.0
  settings:
    build_args:
    - GO_GRAYLOG_VERSION=8.5.4
    - TERRAFORM_VERSION=0.11.14
    password:
      from_secret: quayio_password
    registry: quay.io
    repo: quay.io/suzuki_shunsuke/terraform-graylog
    tags:
    - 8.5.4__0.11.14__${DRONE_TAG##v}
    - 8.5.4__0.11.14
    username:
      from_secret: quayio_username
  when:
    event:
    - tag

- name: test to build docker
  image: plugins/docker:18.09.0
  settings:
    build_args:
    - GO_GRAYLOG_VERSION=8.5.4
    - TERRAFORM_VERSION=0.11.14
    dry_run: true
    registry: quay.io
    repo: quay.io/suzuki_shunsuke/terraform-graylog
  when:
    event:
    - pull_request
    - push

---
kind: pipeline
name: build-0.12.18__8.5.4

platform:
  os: linux
  arch: amd64

steps:
- name: build and push docker
  image: plugins/docker:18.09.0
  settings:
    build_args:
    - GO_GRAYLOG_VERSION=8.5.4
    - TERRAFORM_VERSION=0.12.18
    password:
      from_secret: quayio_password
    registry: quay.io
    repo: quay.io/suzuki_shunsuke/terraform-graylog
    tags:
    - 8.5.4__0.12.18__${DRONE_TAG##v}
    - 8.5.4__0.12.18
    username:
      from_secret: quayio_username
  when:
    event:
    - tag

- name: test to build docker
  image: plugins/docker:18.09.0
  settings:
    build_args:
    - GO_GRAYLOG_VERSION=8.5.4
    - TERRAFORM_VERSION=0.12.18
    dry_run: true
    registry: quay.io
    repo: quay.io/suzuki_shunsuke/terraform-graylog
  when:
    event:
    - pull_request
    - push

...
